import React from "react";
import PropTypes from "prop-types";
import MainLayout from "src/layouts/MainLayout";
import { useRouter } from "next/router";
import type { NextPage } from "next";
import Head from "next/head";
import {
  GetServerSideProps,
  GetServerSidePropsContext,
  PreviewData,
} from "next";
import axios from "axios";
import Image from "next/image";
import YouTube from "react-youtube";
import CustomTabs from "src/components/shared/CustomTabs";
export const getServerSideProps: GetServerSideProps = async (
  context: GetServerSidePropsContext<any, PreviewData>
) => {
  const res = await axios.get(`${process.env.KITSU_URL}/anime`, {
    params: {
      "filter[id]": context.params.index,
    },
  });
  if (!res) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return {
    props: {
      result: res.data,
    }, // will be passed to the page component as props
  };
};
const KitsuAnimeDetails: NextPage = ({ result }) => {
  const router = useRouter();

  return (
    <MainLayout>
      <Head>
        <title>Payndet | Results</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-center items-center">
        {result.data.map((res: any, i: number) => (
          <div className="px-3" key={i}>
            <YouTube
              videoId={res.attributes.youtubeVideoId} // defaults -> null
              className="mt-3 w-full"
              containerClassName="border-red-500"
            />
            <CustomTabs content={res} />
          </div>
        ))}
      </div>
    </MainLayout>
  );
};

KitsuAnimeDetails.propTypes = {};

export default KitsuAnimeDetails;
