import MainLayout from "src/layouts/MainLayout";
import { useRouter } from "next/router";
import type { NextPage } from "next";
import Head from "next/head";
import { Tab, Tabs, TabList, TabPanel } from "react-tabs";
import {
  GetServerSideProps,
  GetServerSidePropsContext,
  PreviewData,
} from "next";
import axios from "axios";
import YouTube from "react-youtube";
import { KitsuDetails } from "../../components/index";
import CustomTabs from "src/components/shared/CustomTabs";
import KitsuReviews from "src/components/home/kitsu/KitsuReviews";

export const getServerSideProps: GetServerSideProps = async (
  context: GetServerSidePropsContext<any, PreviewData>
) => {
  const [detailsResult, reviewsResult] = await Promise.all([
    axios.get(`${process.env.KITSU_URL}/anime`, {
      params: {
        "filter[id]": context.params.index,
      },
    }),
    axios.get(`${process.env.KITSU_URL}/anime/${context.params.index}/reviews`),
  ]);

  return {
    props: {
      detailsRes: detailsResult.data,
      reviewsRes: reviewsResult.data,
    }, // will be passed to the page component as props
  };
};
const KitsuAnimeDetails: NextPage = ({ detailsRes, reviewsRes }) => {
  return (
    <MainLayout>
      <Head>
        <title>Payndet | Results</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col justify-center items-center">
        {detailsRes.data.map((res: any, i: number) => (
          <div className="px-3" key={i}>
            <YouTube
              videoId={res.attributes.youtubeVideoId} // defaults -> null
              className="mt-3 w-full rounded-xl h-60vh"
              containerClassName="border-red-500"
            />
            <h1 className="text-white text-4xl my-5">
              {res.attributes.titles.en_jp}
            </h1>
            <div className="xl:w-90vw flex self-center justify-center items-center">
              <CustomTabs>
                <TabPanel>
                  <KitsuDetails content={res} />
                </TabPanel>
                <TabPanel>
                  <KitsuReviews content={reviewsRes} />
                </TabPanel>
              </CustomTabs>
            </div>
          </div>
        ))}
      </div>
    </MainLayout>
  );
};

export default KitsuAnimeDetails;
