import { MainLayout } from "src/layouts/";
import { useRouter } from "next/router";
import Head from "next/head";
import {
  GetServerSideProps,
  GetServerSidePropsContext,
  PreviewData,
} from "next";
import axios from "axios";
import Image from "next/image";
import { KitsuProps } from "../types";

export const getServerSideProps: GetServerSideProps = async (
  context: GetServerSidePropsContext<any, PreviewData>
) => {
  const res = await axios.get(`${process.env.KITSU_URL}/anime`, {
    params: {
      "filter[text]": context.params.index,
    },
  });
  if (!res) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return {
    props: {
      result: res.data,
    }, // will be passed to the page component as props
  };
};
const KitsuAnimeDetails = ({ result }: KitsuProps) => {
  const router = useRouter();

  return (
    <MainLayout>
      <Head>
        <title>Payndet | Results</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-wrap justify-center items-center">
        {result.data.map((res: any, i: number) => (
          <div
            className="block relative h-96 sm:h-52 w-52 m-5 xl:h-72 xl:w-72"
            key={i}
          >
            <Image
              src={res.attributes.posterImage.original}
              quality={100}
              alt={res.attributes.titles.en_j}
              layout="fill"
            />
            <div className="absolute bottom-0 px-3 flex flex-col justify-start bg-gradient-to-r from-red-500 ">
              <h1 className=" text-white text-xl font-extrabold">
                {res.attributes.titles.en_jp}
              </h1>
              <button className="text-red text-left hover:text-orange">
                See more
              </button>
            </div>
          </div>
        ))}
      </div>
    </MainLayout>
  );
};

export default KitsuAnimeDetails;
